### PR TITLE
Fishing 3.0 dev

### PR DESCRIPTION
**Pull request by Mendaere**
Updated the excellent fishing overhaul mod to work with SMAPI 3.1.0 / SDV 1.4.  Haven't tried to mess with the other mods in the solution except those that fishing overhaul depends on (Core/Core.API/Core.JSON).

### CODE REVIEW

**Comment by TehPers** [comment]
Thank you for creating this. I'll take a look at it at some point, but I recommend [uploading it as an unofficial update](https://stardewvalleywiki.com/Modding:Mod_compatibility#Creating_an_unofficial_update) in the meantime. If you do, make sure to add it to the mod compatibility list on that wiki page as an unofficial update (there's a specific format for them, take a look at the other entries).

**Comment by TehPers** [comment]
I'm trying to compile this with SDV 1.4.5/SMAPI 3.5.0 and I'm getting a few compile errors. In particular, `CraftingPage.pagesOfCraftingRecipes` is inaccessible in `CraftingManager` in the core mod (it's a protected field) and a couple other errors. Which version of SDV are you using?

**Comment by Mendaere** [comment]
I'm currently building with SDV 1.4.5/SMAPI 3.4.2.  Haven't updated to SMAPI 3.5.0 yet, but I don't think that's the source of the build problem you are experiencing (see below).  While I tried messing around with attempting to update to Harmony 2.0, I wasn't able to get that to work.  The mod seems to be ticking along well enough without updating Harmony, so I basically decided "if it ain't broke..." and left it as is.

Note that I'm building in the fishing-3.0-dev branch, not master.  I couldn't figure out how to get the master branch working.  Name notwithstanding, based on the update dates of the various branches I came to the conclusion that the last official version of the Fishing Overhaul mod was built out of fishing-3.0-dev, not master, so I concentrated my efforts there.

As I mentioned in my first commit, I have only updated the parts of the solution that were required in order to build FishingOverhaul, which is why you are getting the crafting manager errors (those come from CoreMod, which FishingOverhaul doesn't use).

To get FishingOverhaul working I found I needed to do Core, Core.API, Core.JSON, and FishingOverhaul itself.  FishingOverhaul.API, CoreMod.API, DependencyResolver, and FishingBomb also build, and so far as I can tell they work.  As mentioned, CoreMod does not build, and so the mods that depend on it (FestiveSlimes, LinkedSkills, and Logistics) don't.

I'll see what I can do about building an unofficial update, as requested.  Might take a day or two.

**Comment by TehPers** [comment]
I unloaded all the projects except the fishing-related projects and it compiles successfully. Yay!

If you upload an unofficial update, do you mind if I put a link to it on the main nexus page? I think very many people will be grateful to see a working version of the mod again. I'll review this PR and potentially merge it in as well, but my next official release is still the fully-rewritten mod.

**Comment by Mendaere** [comment]
Sorry, its been a busy week and only just got back to this.  I have updated to SMAPI 3.5, rebuilt to confirm that the changes work with it and posted the unofficial update, as requested.

**Comment by minervamaga** [comment]
Marked as still compatible with 1.5, however it doesn't seem to be functioning for me and throws errors on loadup: https://smapi.io/log/b03cf933dbae42c78b48d983fe476f68

**Comment by noswanson1982** [comment]
https://forums.stardewvalley.net/attachments/tehpers-fishingoverhaul-2-1-4-zip.2524/ has an unofficial version that works with 1.5.  However, it only has 1.4 features currently and was forked from the version here.  (I didn't make the file on here, I just know it works with 1.5).  However, it won't work with things like Magic Bait or any of the new 1.5 stuff.

**Pull request closed without merging**
